name: 'Build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
            version: 9
            run_install: false
      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
            node-version: 20
            cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: expander-card
          path: |
              dist